import Head from 'next/head'
import Header from '../src/components/header/Header'

export default function Home() {
  return (
    <div className={'class'}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header title='Svent News'/>
    </div>
  )
}
